# Generated by Django 4.2.4 on 2023-11-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferencesutilisateur", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prefernceutilisateur",
            old_name="currency",
            new_name="devise",
        ),
    ]
